spring:
  datasource:
    url: jdbc:mysql://114.55.137.209:3306/youyangblog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: youyangblog
    password: root
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false
  servlet:
    multipart:
      # 单个文件上传最大不得超过2MB
      max-file-size: 2MB
# mybatis
#mybatis:
#  mapper-locations: classpath*:mappers/**/*Mapper.xml
#  type-aliases-package: yu.entity

# pagehelper
#pagehelper:
#  reasonable: true
#  support-methods-arguments: true

#server
server:
  port: 8848